# Generated by Django 5.2.1 on 2025-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_evolucion_habilidad_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
